owner: discord-html
repo: Discord.html-Status

sites:
  - name: Demo
    url: https://discordhtml-demo.daguacaplushy.repl.co
  - name: Beta
    url: $BETA_LINK
  - name: Website
    url: https://discord-html.tk
    
assignees:
  - guacaplushy
  - thecoder876

status-website:
  cname: status.discord-html.tk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Discord.html status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
    - title: Try Discord.html
      href: https://discordhtml-demo.daguacaplushy.repl.co
    - title: Discord
      href: https://discord.gg/W5QserHkTV

# See https://upptime.js.org/docs/configuration for help
