owner: discord-html
repo: Discord.html-Status

sites:
  - name: Demo
    url: https://discordhtml-demo.daguacaplushy.repl.co
  - name: Beta
    url: $BETA_LINK
  - name: Website
    url: https://discord-html.tk
  - name: Status
    url: https://status.discord-html.tk
  - name: Message API
    url: https://discordhtml-api.guacaplushy2.repl.co
    
assignees:
  - guacaplushy
  - thecoder876

status-website:
  cname: status.discord-html.tk
  logoUrl: https://raw.githubusercontent.com/discord-html/Discord.html-Status/master/assets/logo.png
  name: Discord.html status
  theme: dark
  navbar:
    - title: Website
      href: https://discord-html.tk
    - title: GitHub
      href: https://github.com/$OWNER/
    - title: Try Discord.html
      href: https://discordhtml-demo.daguacaplushy.repl.co
    - title: Discord
      href: https://discord.gg/W5QserHkTV
