owner: discord-html
repo: Discord.html-Status
BETA_LINK: https://discordhtml.daguacaplushy.repl.co

sites:
  - name: Demo
    url: https://discordhtml-demo.daguacaplushy.repl.co
  - name: Beta
    url: $BETA_LINK
  - name: Website
    url: https://discord-html.tk
  - name: Status
    url: https://status.discord-html.tk
    
assignees:
  - guacaplushy
  - thecoder876

status-website:
  cname: status.discord-html.tk
  logoUrl: https://discord-html.tk/assets/logo.png
  name: Discord.html status
  theme: dark
  navbar:
    - title: Website
      href: https://discord-html.tk
    - title: GitHub
      href: https://github.com/$OWNER/
    - title: Try Discord.html
      href: https://discordhtml-demo.daguacaplushy.repl.co
    - title: Discord
      href: https://discord.gg/W5QserHkTV

# See https://upptime.js.org/docs/configuration for help.
